Added the mission manager module
sonia-auv/octopus-telemetry pull request #52
Opened 2021-03-15 20:14 UTC by alexemdesgagne

**Warning :** Before creating a pull request, make sure that it does not already exists in the [pull requests](../). Thank you.

## Description
I added the mission manager module.

## Fixes
Link all the related issues from the issue tracker
- Closes: #

## How has this been tested ?
(If possible) describe the steps to test these modifications.

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-03-16 01:37 UTC, antho6222 requested changes

2021-03-16 01:37 UTC, antho6222 commented on src/src/components/MissionManager.tsx
> +            console.log("List missions");
On évite de laisser des console.log dans Master

2021-03-16 01:37 UTC, antho6222 commented on src/src/components/MissionManager.tsx
> +            console.log(missionsList);
retirer console.log

2021-03-16 01:37 UTC, antho6222 commented on src/src/components/MissionManager.tsx
> +        console.log("Mission selected: " + event.target.value as string)
retirer console.log

2021-03-16 01:37 UTC, antho6222 commented on src/src/components/MissionManager.tsx
> +        console.log(toPublish);
retirer console.log

2021-03-16 01:37 UTC, antho6222 commented on src/src/components/MissionManager.tsx
> +        console.log("Update mission list")
retirer console.log

2021-03-16 01:37 UTC, antho6222 commented on src/src/components/MissionManager.tsx
> +    const [currentMissionName, setCurrentMissionName] = useState('Example Behavior');
Pourquoi  mettre la valeur initiale "Example Behavior"?

2021-03-16 01:37 UTC, antho6222 commented on src/src/components/MissionManager.tsx
> +        console.log("Load mission: " + currentMissionName);
retirer console.log

2021-03-16 01:37 UTC, antho6222 commented on src/src/components/MissionManager.tsx
> +    // // Update de la liste de missions a l ouverture de la page.
Pense tu avoir besoin de ce code encore?

2021-03-16 01:37 UTC, antho6222 commented on src/src/components/MissionManager.tsx
> +    const missionListCallback = useCallback(
J'ai pas pu encore tester les callbacks des services, avais tu réussis ? dans notre code on avait plutôt useCallback(
        (x: any) => { , je sais pas si on a besoin de : response: ROSLIB.ServiceResponse? , je ne suis pas sur ici on aurait peut être pu utiliser x qui contient le message de callback avec les infos ? à voir c'est une supposition, dans tout nos modules on a utilisé cette manière de faire sans encore la tester, mais c'est histoire d'être uniforme partout.

2021-03-16 01:37 UTC, antho6222 commented on src/src/components/MissionManager.tsx
> +                        <InputLabel id="demo-simple-select-outlined-label">Mission</InputLabel>
changer "demo" par "missionManager" par exemple

2021-03-16 01:37 UTC, antho6222 commented on src/src/components/MissionManager.tsx
> +                <div style={{ width: '100%', height: '100%', flexDirection: 'row', backgroundColor: '#85D2BB', textAlign: 'center' }}>
Tu peux retirer background color, sinon ton fond va rester vert et il ne suivra pas le dark theme (ou autre theme)

2021-03-18 01:59 UTC, alexemdesgagne commented on src/src/components/MissionManager.tsx
> +    const missionListCallback = useCallback(
Ici, j'ai fait l'utilisation response:ROSLIB.ServiceResponse pour spécifier explicitement le type de l'objet que je m'attends de recevoir. Je crois qu'aujourd'hui, Laurent a mentionné de repasser au travers des any pour les remplacer.

2021-03-18 02:34 UTC, alexemdesgagne commented on src/src/components/MissionManager.tsx
> +    // // Update de la liste de missions a l ouverture de la page.
Effectivement, je n'en ai plus besoin.

2021-04-07 03:55 UTC, closed without merging